version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: travelmate-server/Dockerfile
    container_name: travelmate-backend
    ports:
      - '5000:5000'
    env_file:
      - ./travelmate-server/.env
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: travelmate-client/Dockerfile
    container_name: travelmate-frontend
    ports:
      - '80:80'  # Expose on host port 3000
    depends_on:
      - backend
    restart: unless-stopped

  mongo:
    image: mongo
    container_name: travelmate-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
